### ISSUE TITLE
Support integers instead of changing them to doubles/floats/decimals.

### ISSUE THREAD

**Issue by josephspurrier** [jsonsystems/json-schema#78] opened 2020-04-18 20:58 UTC
When I paste in this code to the generator (https://jsonschema.net/home), it comes back with an example that says 1.0 instead of 1.

```json
{
    "id": 1
}
```

Here is what comes back:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "additionalProperties": true,
    "required": [
        "id"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "integer",
            "title": "The Id Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                1.0
            ]
        }
    }
}
```

Is there a way for the example to not have a decimal?

**Comment by jsonsystems** [comment] 2020-04-19 18:33
@josephspurrier Another good issue and thanks for posting it.  This has been on my list of tasks for some time. It's caused by the use of Google's Protocol Buffers on the backend which converts everything to a `number`:

```python
from google.protobuf import json_format, struct_pb2

if __name__ == '__main__':
    list_value = struct_pb2.ListValue()
    list_value.append(1)
    result = json_format.MessageToDict(list_value)
    print(result)
```

Running this Python code outputs: `[1.0]`. The `examples` keyword is implemented using [ListValue](https://developers.google.com/protocol-buffers/docs/reference/python-generated#listvalue).

I am going to look at this again and see if there's a reasonably nice way around it.

**Comment by jsonsystems** [comment] 2020-05-10 20:02
@josephspurrier I'm working on significant improvements to the `examples`, `default`, `const`, and `enum` keywords which will fix this. I'll keep this issue updated.

**Comment by jsonsystems** [comment] 2020-05-12 17:58
@josephspurrier I've improved the handling of types on www.jsonschema.net. Does it not behave as you wanted?

**Comment by jsonsystems** [comment] 2020-05-17 09:37
Closing this as it's now working and there's not update from OP.

**Closed by jsonsystems** 2020-05-17 09:37 UTC
