### ISSUE TITLE
It can't create json schema according to the given json

### ISSUE THREAD

**Issue by JDaisy** [jsonsystems/json-schema#100] opened 2020-09-28 06:26 UTC
errro message is：Http failure response for https://prod.json.systems/v1/graphs:inferGraph: 0 Unknown Error

**Comment by DSuds** [comment] 2020-09-30 11:43
I think posting the json you are referring to would make this more understandable.  I'm not sure if you are trying to suggest a content issue or an access issue.

**Comment by JDaisy** [comment] 2020-10-26 12:12
> I think posting the json you are referring to would make this more understandable. I'm not sure if you are trying to suggest a content issue or an access issue.

sorry，I will describe it more particular：
![image](https://user-images.githubusercontent.com/18110258/97169819-ab028f80-17c5-11eb-8a32-05bed9aa7fbe.png)
then I have a long wait……
20 minutes later，It's still in a waiting state
at last，I get an error message：Http failure response for https://prod.json.systems/v1/graphs:inferGraph: 0 Unknown Error

**Comment by JDaisy** [comment] 2020-10-27 03:25
> I think posting the json you are referring to would make this more understandable. I'm not sure if you are trying to suggest a content issue or an access issue.

error screenshot:
![image](https://user-images.githubusercontent.com/18110258/97253263-ef823f80-1846-11eb-9a7c-14a7537b305c.png)

**Comment by jsonsystems** [comment] 2020-11-10 10:26
@JDaisy Thanks for the screenshots, can you post your **raw JSON** here so I can recreate the error?

**Comment by MarcellHarmaci** [comment] 2020-11-11 18:41
Same issue here, but I always get the error in a very short time. It worked with the base example at first. After I changed it to my own json I got the same error. Now it doesn't work with anything. Even after pushing the "RESET" button I get the error for the example json too.
![image](https://user-images.githubusercontent.com/47602777/98850759-8b21cb80-2455-11eb-9859-f1f4c410f7a5.png)

**Comment by jsonsystems** [comment] 2020-11-14 12:24
@MarcellHarmaci This is a problem with the JWT decode code. I've added extra logging to the application which should help me track down the root cause. Thank you for your patience.

**Comment by jsonsystems** [comment] 2020-11-14 12:54
@MarcellHarmaci Can you try www.jsonschema.net and let me know if it now works for you? I don't know about the other issues posted here, but I believe yours should be fixed.

**Comment by MarcellHarmaci** [comment] 2020-11-15 10:51
@jsonschemr Sure! You are correct. My issue is resolved. Thank you!

**Closed** 2020-11-15 11:14 UTC
Labels: question
