### ISSUE TITLE
feature request: cli / package for infer

### ISSUE THREAD

**Issue by refactorized** [jsonsystems/json-schema#58] opened 2019-09-06 19:46 UTC
I would love to be able to use this tool offline or programatically.  If I could pass in an options object and some json and get a schema out of it, I could put it into a build process for my current endeavor, and that would make me happy.  

(I am, bit by bit, altering an old format and creating a schema out of the new format)

It's probably a 'no' but I figure I would ask.  Perhaps you could open source the inference with the stipulation that people don't just build a clone of your site?

Thanks

**Comment by jackwootton** [comment] 2019-09-18 08:31
This is a good idea. An API is planned for release this year. But perhaps people would prefer a pip package?

**Comment by steder** [comment] 2019-10-10 05:28
I would ❤️ a pip package.

**Comment by jsonsystems** [comment] 2020-05-17 10:14
Duplicate of #30.

Thanks for expressing an interest in the source code or a package. To avoid this slipping down my list again I'm merging with #30.

**Closed by jsonsystems** 2020-05-17 10:14 UTC
Labels: duplicate
