### ISSUE TITLE
CLI for generating JSON Schema from JSON

### ISSUE THREAD

**Issue by abdul-thoughtworks** [jsonsystems/json-schema#73] opened 2020-03-14 09:02 UTC
Do we have a CLI for generating JSON Schema from JSON, This would be highly beneficial .

**Comment by jackwootton** [comment] 2020-03-16 11:15
Thanks for the feature request. Eventually I would like to package the application so it can be installed with pip. However right now my focus is on the web application so less technical users can just copy-paste without coding knowledge.

I'll tag this as an enhancement to track it.

**Comment by pmgupte** [comment] 2020-03-19 14:08
+1 for FR. I am planning to improve (drastically) my [content monitoring utility](https://github.com/pmgupte/webmon/blob/master/README.md) pet project, and wanted exactly what you have here! If CLI is available, I would like to use it in the planned improvement.

**Comment by rquintanilla-amp** [comment] 2020-05-01 00:24
Or just some NPM modules so that we can call this programmatically?

**Comment by jsonsystems** [comment] 2020-05-17 10:15
Duplicate of #30.

Thanks for expressing an interest in the source code or a package. To avoid this slipping down my list again I'm merging with #30.

**Closed by jsonsystems** 2020-05-17 10:15 UTC
Labels: enhancement
